languageCode = "es-ar"
title = "Gzalo"
theme = "gzalo"
disqusShortname = "gzalo"
defaultContentLanguage = "es"

[minify]
  minifyOutput = true

[languages]
  [languages.es]
    languageName = "Español"
    description = "Electrónica, programación y otras cosas"
    weight = 1
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Calculadoras"
        url = "/calculators/"
        weight = 1
        pre = "border-sky-700 text-sky-700"
      [[languages.es.menu.main]]
        name = "Artículos"
        url = "/articles/"
        weight = 2
        pre = "border-red-600 text-red-600"
      [[languages.es.menu.main]]
        name = "Proyectos"
        url = "/projects/"
        weight = 3
        pre = "border-orange-700 text-orange-700"
      [[languages.es.menu.main]]
        name = "Experimentos"
        url = "/experiments/"
        weight = 4
        pre = "border-emerald-700 text-emerald-700"
      [[languages.es.menu.main]]
        name = "Sobre mí"
        url = "/about/"
        weight = 5
        pre = "border-black"
      [[languages.es.menu.main]]
        name = "SearchIcon"
        url = "/search/"
        weight = 6
        pre = "border-black"        

  [languages.en]
    languageName = "English"
    description = "Electronics, programming & other stuff"
    weight = 2
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Calculators"
        url = "/en/calculators/"
        weight = 1
        pre = "border-sky-700 text-sky-700"
      [[languages.en.menu.main]]
        name = "Articles"
        url = "/en/articles/"
        weight = 2
        pre = "border-red-600 text-red-600"
      [[languages.en.menu.main]]
        name = "Projects"
        url = "/en/projects/"
        weight = 3
        pre = "border-orange-700 text-orange-700"
      [[languages.en.menu.main]]
        name = "Experiments"
        url = "/en/experiments/"
        weight = 4
        pre = "border-emerald-700 text-emerald-700"
      [[languages.en.menu.main]]
        name = "About me"
        url = "/en/about/"
        weight = 5  
        pre = "border-black"
      [[languages.en.menu.main]]
        name = "SearchIcon"
        url = "/en/search/"
        weight = 6
        pre = "border-black"             
