languageCode = "es-ar"
title = "Gzalo"
theme = "gzalo"
disqusShortname = "gzalo"
defaultContentLanguage = "es"

[languages]
  [languages.es]
    languageName = "Español"
    description = "Electrónica, programación y otras cosas"
    weight = 1
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Calculadoras"
        url = "/calculators/"
        weight = 1
        pre = "border-sky-400 text-sky-400"
      [[languages.es.menu.main]]
        name = "Artículos"
        url = "/articles/"
        weight = 2
        pre = "border-red-500 text-red-500"
      [[languages.es.menu.main]]
        name = "Proyectos"
        url = "/projects/"
        weight = 3
        pre = "border-orange-400 text-orange-400"
      [[languages.es.menu.main]]
        name = "Experimentos"
        url = "/experiments/"
        weight = 4
        pre = "border-emerald-500 text-emerald-500"
      [[languages.es.menu.main]]
        name = "Acerca"
        url = "/about/"
        weight = 5

  [languages.en]
    languageName = "English"
    description = "Electronics, programming & other stuff"
    weight = 2
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Calculators"
        url = "/en/calculators/"
        weight = 1
        pre = "border-sky-400 text-sky-400"
      [[languages.en.menu.main]]
        name = "Articles"
        url = "/en/articles/"
        weight = 2
        pre = "border-red-500 text-red-500"
      [[languages.en.menu.main]]
        name = "Projects"
        url = "/en/projects/"
        weight = 3
        pre = "border-orange-400 text-orange-400"
      [[languages.en.menu.main]]
        name = "Experiments"
        url = "/en/experiments/"
        weight = 4
        pre = "border-emerald-500 text-emerald-500"
      [[languages.en.menu.main]]
        name = "About"
        url = "/en/about/"
        weight = 5  
